version: '3.8'
services:
    redis-keys-master:
        image: redis:latest
        deploy:
            replicas: 1
        container_name: redis-keys-master
        ports:
            - 6379:6379
    redis-keys-slave:
        image: redis:latest
        command: redis-server --port 6380 --slaveof redis-keys-master 6379 --replica-read-only no
        deploy:
            replicas: 1
        container_name: redis-keys-slave
        ports:
            - 6380:6380
        depends_on:
            - redis-keys-master

    redis-request-master:
        image: redis:latest
        command: redis-server --port 6381
        deploy:
            replicas: 1
        container_name: redis-request-master
        ports:
            - 6381:6381
    redis-request-slave:
        image: redis:latest
        command: redis-server --port 6382 --slaveof redis-request-master 6381 --replica-read-only no
        deploy:
            replicas: 1
        container_name: redis-request-slave
        ports:
            - 6382:6382
        depends_on:
            - redis-request-master

    redis-response-master:
        image: redis:latest
        command: redis-server --port 6383
        deploy:
            replicas: 1
        container_name: redis-response-master
        ports:
            - 6383:6383
    redis-response-slave:
        image: redis:latest
        command: redis-server --port 6384 --slaveof redis-response-master 6383 --replica-read-only no
        deploy:
            replicas: 1
        container_name: redis-response-slave
        ports:
            - 6384:6384
        depends_on:
            - redis-response-master